### ISSUE TITLE
Item barcode uniqueness check doesn't work anymore

### ISSUE THREAD

**Issue by iGormilhit** [rero/reroils-record-editor#3]
On ils.test.rero.ch, v.0.1.0a11, the item barcode uniqueness check doesn't work any more. 
See: https://ils.test.rero.ch/documents/11
![capture_085](https://user-images.githubusercontent.com/1557213/38813945-94d4766e-4190-11e8-98f7-3511f005fc12.png)

**Comment by pronguen** [comment]
By adding an new item, we receive the message "Error: Cannot retrieve the record (item).". But the item is created.
By deleting an item, we get the page "Internal server error". But the item is deleted.

**Comment by iGormilhit** [comment]
As @jma pointed, the test works when creating an item, but doesn't when editing it.

**Comment by iGormilhit** [comment]
This is fixed by https://github.com/rero/reroils-app/commit/4fa9c0b9a9d82dca89732d0588460722c97801d9 and https://github.com/rero/reroils-data/commit/454b312e9f7229946b9e00058357a9a64944602c
